// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorHtyjNJ5LyWczcjhTXjpEcPJFnkQR6k',
    appId: '1:1028629178150:web:d68e9e1631e0b19d67c3e7',
    messagingSenderId: '1028629178150',
    projectId: 'kafee-2466b',
    authDomain: 'kafee-2466b.firebaseapp.com',
    storageBucket: 'kafee-2466b.firebasestorage.app',
    measurementId: 'G-ELKDCRDR2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH3wiTPR5Q4YjILpZBvgTR-qOtWScT_MI',
    appId: '1:1028629178150:android:ef6ac857cf39eb0467c3e7',
    messagingSenderId: '1028629178150',
    projectId: 'kafee-2466b',
    storageBucket: 'kafee-2466b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9BdwudXk9XGMdVkIKBuZ-yhDvpqA22Ts',
    appId: '1:1028629178150:ios:1eb2a938ae7740da67c3e7',
    messagingSenderId: '1028629178150',
    projectId: 'kafee-2466b',
    storageBucket: 'kafee-2466b.firebasestorage.app',
    iosBundleId: 'com.example.kafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9BdwudXk9XGMdVkIKBuZ-yhDvpqA22Ts',
    appId: '1:1028629178150:ios:1eb2a938ae7740da67c3e7',
    messagingSenderId: '1028629178150',
    projectId: 'kafee-2466b',
    storageBucket: 'kafee-2466b.firebasestorage.app',
    iosBundleId: 'com.example.kafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDorHtyjNJ5LyWczcjhTXjpEcPJFnkQR6k',
    appId: '1:1028629178150:web:6be1609a8f1df6ea67c3e7',
    messagingSenderId: '1028629178150',
    projectId: 'kafee-2466b',
    authDomain: 'kafee-2466b.firebaseapp.com',
    storageBucket: 'kafee-2466b.firebasestorage.app',
    measurementId: 'G-WQF6YYMBST',
  );
}
